import { PackResult, ContextPackOptions } from './types.js';
import { formatTokenCount, getContextWarning } from './tokenEstimator.js';

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}

export function formatMarkdown(result: PackResult, options: ContextPackOptions): string {
  const warning = getContextWarning(result.totalTokens);
  const lines: string[] = [];

  // Header
  lines.push('# ContextPack');
  lines.push('');
  lines.push(`> Generated by [contextpack](https://github.com/HalxDocs/contextpack) — ${result.generatedAt}`);
  lines.push('');

  // Stats
  lines.push('## 📊 Stats');
  lines.push('');
  lines.push(`| Property | Value |`);
  lines.push(`|----------|-------|`);
  lines.push(`| Source | \`${result.sourceDir}\` |`);
  lines.push(`| Files | ${result.totalFiles} |`);
  lines.push(`| Total Size | ${formatBytes(result.totalSizeBytes)} |`);
  lines.push(`| Estimated Tokens | ${formatTokenCount(result.totalTokens)} |`);
  lines.push('');

  if (warning) {
    lines.push(`> ${warning}`);
    lines.push('');
  }

  // File Tree
  lines.push('## 🗂 File Tree');
  lines.push('');
  lines.push('```');
  lines.push(result.fileTree);
  lines.push('```');
  lines.push('');

  // Files
  lines.push('## 📄 Files');
  lines.push('');

  for (const file of result.files) {
    lines.push(`### \`${file.relativePath}\``);
    lines.push('');
    lines.push(`> ${formatBytes(file.sizeBytes)} · ${formatTokenCount(file.tokens)}`);
    lines.push('');
    lines.push(`\`\`\`${file.language}`);
    lines.push(file.content);
    lines.push('```');
    lines.push('');
  }

  return lines.join('\n');
}

export function formatJSON(result: PackResult): string {
  return JSON.stringify(
    {
      meta: {
        generatedAt: result.generatedAt,
        sourceDir: result.sourceDir,
        totalFiles: result.totalFiles,
        totalSizeBytes: result.totalSizeBytes,
        totalTokens: result.totalTokens,
      },
      fileTree: result.fileTree,
      files: result.files.map(f => ({
        path: f.relativePath,
        language: f.language,
        sizeBytes: f.sizeBytes,
        tokens: f.tokens,
        content: f.content,
      })),
    },
    null,
    2
  );
}